// <auto-generated />
using DeliveryRouting.SQLData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DeliveryRouting.WebApi.Migrations
{
    [DbContext(typeof(DeliveryRoutingContext))]
    partial class DeliveryRoutingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeliveryRouting.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("AssignmentNotes");

                    b.Property<string>("City");

                    b.Property<string>("Cm");

                    b.Property<string>("FamilyId");

                    b.Property<string>("FirstName");

                    b.Property<string>("InformationUpdateNotes");

                    b.Property<string>("InitialId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("Notes");

                    b.Property<string>("NumberAttendingThanksgiving");

                    b.Property<string>("Phone");

                    b.Property<string>("RouteAssignment");

                    b.Property<int?>("RouteId");

                    b.Property<string>("State");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("DeliveryRouting.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RouteName");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("DeliveryRouting.Models.Family", b =>
                {
                    b.HasOne("DeliveryRouting.Models.Route", "Route")
                        .WithMany("Addresses")
                        .HasForeignKey("RouteId");
                });
#pragma warning restore 612, 618
        }
    }
}
